name: eds-lessons
channels:
  - conda-forge
dependencies:
  - papermill
  - pip=19.0.3

  # Core scientific python
  - numpy
  - matplotlib
  - pip
  - python=3.6
  - pyqt
  - scikit-learn
  - seaborn

  # extentions
  - autopep8

  # Geo stuff
  - basemap
  - cartopy
  - contextily
  - earthpy
  - folium
  - gdal
  - geocoder
  - geojson
  - geopandas
  - geopy
  - libgdal
  - libiconv
  - pyproj
  - pysal
  - rasterio
  - rasterstats
  - scikit-image
  - shapely

  # natural language processing
  - nltk
  - tweepy

  # Jupyter Environment
  - ipython
  - notebook

  - pip:
      # Utilities
      - cenpy
      - climata
      - elevation
      - hydrofunctions
      - mapboxgl
      - nbclean
      - richdem
