name: eds-lessons
channels:
  - conda-forge
dependencies:
  - papermill

  # Core scientific python
  - numpy
  - matplotlib
  - pip
  - python=3.6
  - pyqt
  - scikit-learn
  - seaborn

  # extentions
  - autopep8

  # Geo stuff
  - rasterstats
  - geopy
  - cartopy
  - geopandas
  - rasterio
  - libiconv
  - contextily
  - pysal
  - pyproj
  - folium
  - scikit-image
  - gdal
  - libgdal
  - geocoder
  - geojson
  - basemap
  - shapely
  - earthpy

  # natural language processing
  - tweepy
  - nltk

  # Jupyter Environment
  - notebook
  - ipython

  - pip:
      # Utilities
      # - download
      # - nbgrader
      - nbclean
      # - mne
      # - tqdm
      # - kiwisolver
      # more ea stuff
      - mapboxgl
      - hydrofunctions
      # tutorials
      - cenpy
      - climata
      - elevation
      - richdem
